### ISSUE TITLE
What should happen when a post gets massive negative feedback?

### ISSUE THREAD

**Issue by Goga-Barabadze** [Goga-Barabadze/shelley#1]
- Delete it?
    - Deleting something should be a last measure as it would conflict with our transparency philosophy.
    - Only delete things are clearly against the use-case of the platform (e.g. advertisement)
    - Unpopular (but potentially true) opinions would not have a chance
- Fade it out (as Stackoverflow does)?
    - That would make it harder for the post to recover if it turns out to be accurate later on.
- Leave it untouched?
    - We should design a system which makes good arguments float to the top. Bad arguments should remain but "naturally" go under

**Comment by Elisa-Oropeza** [comment]
"Leave it untouched" sounds good.
Also, the feedback / rating of the post should be visible to users (so that they are aware of said negative feedback).

**Comment by Goga-Barabadze** [comment]
Agreed. Will close this issue
